projects:
  photoalbums:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 25hijjsvdbcy3n5sbossroir4m
      endpoints:
        prod: >-
          https://fptqeo6xxfeupfj3oh7p7d5wgu.appsync-api.us-east-2.amazonaws.com/graphql
